{% set name = "pypsexec" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pypsexec-{{ version }}.tar.gz
  sha256: 84a21aa8984847a1616cdb6b47c36d20c43b90996f8894996d4939db2e78ddc2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - smbprotocol

test:
  imports:
    - pypsexec
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jborean93/pypsexec
  summary: Run commands on a remote Windows host using SMB/RPC
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nehaljwani
